import { AppBar, Tab, Tabs, Toolbar, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import BusButton from '../components/button'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [tabValue, setTabValue] = React.useState(0);
  const [isOn, setIsOn] = React.useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>次止まります</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar>
          <Toolbar>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              次止まりますボタン
            </Typography>
            <Tabs value={tabValue} onChange={(_, newValue) => setTabValue(newValue)}>
              <Tab label="Audience" />
              <Tab label="Presenter" />
            </Tabs>
          </Toolbar>
        </AppBar>
        <BusButton isOn={isOn} onClick={() => setIsOn(!isOn)} />
      </main>
    </div>
  )
}

export default Home
